[smartstore_mirrorball]
title = "네이버 스마트스토어 ─ 미러볼뮤직"
url = "https://smartstore.naver.com/mirrorballmusic/category/ALL?cp=1"
entrySelector = "ul li.-qHwcFXhj0"
titleSelector = "strong.QNNliuiAk3"
linkSelector = "a"
imageSelector = "img._25CKxIKjAk"
contentSelector = "div._23DThs7PLJ span.nIAdxeTzhx"
waitUntil = "networkidle"

[smartstore_hionerecords]
title = "네이버 스마트스토어 ─ 하이원레코드"
url = "https://smartstore.naver.com/hionerecords/category/05886edde4784afbb1efefc18afbc298?cp=1"
entrySelector = "ul li.-qHwcFXhj0"
titleSelector = "strong.QNNliuiAk3"
linkSelector = "a"
imageSelector = "img._25CKxIKjAk"
contentSelector = "div._23DThs7PLJ span.nIAdxeTzhx"
waitUntil = "networkidle"

[smartstore_hyangmusic]
title = "네이버 스마트스토어 ─ 향뮤직"
url = "https://smartstore.naver.com/hyangmusic/category/32562d12fd7b46f2835fcb246ba18ce1?cp=1"
entrySelector = "ul li.-qHwcFXhj0"
titleSelector = "strong.QNNliuiAk3"
linkSelector = "a"
imageSelector = "img._25CKxIKjAk"
contentSelector = "div._23DThs7PLJ span.nIAdxeTzhx"
waitUntil = "networkidle"

[smartstore_gongsangondo]
title = "네이버 스마트스토어 ─ 공상온도"
url = "https://smartstore.naver.com/gongsangondo/category/593714ce0fbf46cabd0c3f8da4976cfe"
entrySelector = "ul li.-qHwcFXhj0"
titleSelector = "strong.QNNliuiAk3"
linkSelector = "a"
imageSelector = "img._25CKxIKjAk"
contentSelector = "div._23DThs7PLJ span.nIAdxeTzhx"
waitUntil = "networkidle"

[smartstore_studiozemi]
title = "네이버 스마트스토어 ─ 재미공작소"
url = "https://smartstore.naver.com/studiozemi/category/ALL?cp=1"
entrySelector = "ul li.-qHwcFXhj0"
titleSelector = "strong.QNNliuiAk3"
linkSelector = "a"
imageSelector = "img._25CKxIKjAk"
contentSelector = "div._23DThs7PLJ span.nIAdxeTzhx"
waitUntil = "networkidle"

[smartstore_strangetiger]
title = "네이버 스마트스토어 ─ 스트레인지 "
url = "https://smartstore.naver.com/strangetiger/category/6532e4ab92df4f9c92276fc700f26a7b?cp=1"
entrySelector = "ul li.-qHwcFXhj0"
titleSelector = "strong.QNNliuiAk3"
linkSelector = "a"
imageSelector = "img._25CKxIKjAk"
contentSelector = "div._23DThs7PLJ span.nIAdxeTzhx"
waitUntil = "networkidle"
